---
# tasks file for docker-monitoring

- name: Ensure /opt/cybersift/docker-monitoring directory exists
  file:
    path: "{{ stack_path }}"
    state: directory

- name: Ensure stack compose file exists on the target server
  copy:
    src: "{{ role_path }}/files/docker-compose.yml"
    dest: "{{ stack_path }}"

- name: Ensure the stack is up
  shell: "docker-compose up -d"
  args:
    chdir: "{{ stack_path }}"

