---
# tasks file for docker-monitoring

- name: Ensure /opt/cybersift/docker-monitoring directory exists
  file:
    path: "{{ stack_path }}"
    state: directory

- name: Ensure stack compose file exists on the target server
  copy:
    src: "{{ role_path }}/files/docker-compose.yml"
    dest: "{{ stack_path }}"

- name: Ensure the stack is up
  shell: "docker-compose up -d"
  args:
    chdir: "{{ stack_path }}"

- name: Ensure InfluxData repository is installed
  shell: wget -q https://repos.influxdata.com/influxdata-archive_compat.key ; echo '393e8779c89ac8d958f81f942f9ad7fb82a25e133faddaf92e15b16e6ac9ce4c influxdata-archive_compat.key' | sha256sum -c && cat influxdata-archive_compat.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/influxdata-archive_compat.gpg > /dev/null ; echo 'deb [signed-by=/etc/apt/trusted.gpg.d/influxdata-archive_compat.gpg] https://repos.influxdata.com/debian stable main' | sudo tee /etc/apt/sources.list.d/influxdata.list

- name: Ensure apt cache is updated
  apt:
    update_cache: yes

- name: Ensure Telegraf is installed
  apt:
    name: telegraf
    state: present

- name: Ensure telegraf.conf is copied
  copy:
    src: "{{ role_path }}/files/telegraf.conf"
    dest: "/etc/telegraf/"
    owner: root
    group: root
    mode: '0644'
  notify: Restart telegraf

- name: Ensure telegraf service is enabled and started
  service:
    name: telegraf
    enabled: true
    state: started

