---
# tasks file for docker_nifi

- name: Ensure /opt/cybersift/docker_nifi directory exists
  file:
    path: "{{ stack_path }}"
    state: directory

- name: Ensure stack compose file exists on the target server
  template:
    src: "docker-compose.yml.j2"
    dest: "{{ stack_path }}/docker-compose.yml"

- name: Ensure the stack is up
  shell: "docker-compose up -d"
  args:
    chdir: "{{ stack_path }}"

- name: Ensure rsyslog is configured to send logs to NiFi
  copy:
    dest: "/etc/rsyslog.d/nifi.conf"
    content: >
      *.* action(type="omfwd" target="localhost" port="10514" protocol="udp")
  notify: Restart rsyslog.service
