---
# tasks file for docker-elastic

- name: Ensure stack directory (docker-elk) exists
  copy:
    src: "{{ role_path }}/files/docker-elk"
    dest: "{{ stack_path }}"

- name: Ensure stack compose file exists
  template:
    src: "docker-compose.yml.j2"
    dest: "{{ stack_path }}/docker-elk/docker-compose.yml"

- name: Ensure stack compose env file exists
  template:
    src: ".env.j2"
    dest: "{{ stack_path }}/docker-elk/.env"

- name: Ensure docker-elk/setup/entrypoint.sh file is executable
  file:
    path: "{{ stack_path }}/docker-elk/setup/entrypoint.sh"
    mode: '0754'

- name: Ensure the stack is up
  shell: "docker-compose up setup ; docker-compose up -d"
  args:
    chdir: "{{ stack_path }}/docker-elk"
