---
# tasks file for docker_monitoring

- name: Ensure /opt/cybersift/docker_monitoring directory exists
  file:
    path: "{{ stack_path }}"
    state: directory

- name: Ensure stack compose file exists
  template:
    src: "docker-compose.yml.j2"
    dest: "{{ stack_path }}/docker-compose.yml"

- name: Ensure the stack is up
  shell: "docker-compose up -d"
  args:
    chdir: "{{ stack_path }}"

- name: Ensure Grafana UI (http://{{ inventory_hostname }}:{{ grafana_host_port }}/) is available
  uri:
    url: "http://localhost:{{ grafana_host_port }}/"
    method: GET
    status_code:
      - 200
  register: uri_output
  until: uri_output.status == 200
  retries: 12 # Retries for 12 * 5 seconds = 60 seconds
  delay: 5 # Retry every 5 seconds

- name: Ensure Grafana admin user password is changed
  uri:
    url: "http://{{ grafana_host }}:{{ grafana_host_port }}/api/user/password"
    user: "{{ grafana_security_admin_user }}"
    password: "admin"
    force_basic_auth: true
    method: PUT
    body_format: json
    body: >
      {
        "oldPassword":"admin",
        "newPassword":"{{ grafana_security_admin_password }}"
      }
    status_code:
      - 200
  register: uri_output
  until: uri_output.status == 200
  retries: 12 # Retries for 12 * 5 seconds = 60 seconds
  delay: 5 # Retry every 5 seconds

- name: Check if Grafana InfluxDB datasource exists
  uri:
    url: "http://{{ grafana_host }}:{{ grafana_host_port }}/api/datasources/name/InfluxDB"
    user: "{{ grafana_security_admin_user }}"
    password: "{{ grafana_security_admin_password }}"
    force_basic_auth: true
    method: GET
    status_code: [200, 404]
  register: datasource_check

- name: Ensure Grafana InfluxDB datasource is added
  uri:
    url: "http://{{ grafana_host }}:{{ grafana_host_port }}/api/datasources"
    user: "{{ grafana_security_admin_user }}"
    password: "{{ grafana_security_admin_password }}"
    force_basic_auth: true
    method: POST
    body_format: json
    body: >
      {
        "org_id": 1,
        "name": "InfluxDB",
        "type": "influxdb",
        "access": "proxy",
        "url": "http://influxdb:8086",
        "database": "{{ influxdb_db_name }}",
        "basicAuth": true,
        "basicAuthUser": "{{ influxdb_admin_user }}",
        "secureJsonData": {
          "basicAuthPassword": "{{ influx_db_admin_password }}"
        }
      }
    status_code:
      - 200
  when: datasource_check.status != 200
  register: influxdb_ds_result

- name: Ensure 'Telegraf - system metrics' dashboard exists
  uri:
    url: "http://{{ grafana_host }}:{{ grafana_host_port }}/api/dashboards/db"
    user: "{{ grafana_security_admin_user }}"
    password: "{{ grafana_security_admin_password }}"
    force_basic_auth: true
    method: POST
    body_format: json
    body: "{{ lookup('template', 'telegraf-system-metrics.json.j2') }}"
    status_code:
      - 200
