---
- name: Include docker.yml play
  import_playbook: plays/docker.yml

- name: Include docker-elastic.yml play
  import_playbook: plays/docker-elastic.yml

- name: Include docker-nifi.yml play
  import_playbook: plays/docker-nifi.yml

- name: Include docker-monitoring.yml play
  import_playbook: plays/docker-monitoring.yml
