---
# tasks file for docker_elastic

- name: Ensure stack directory (docker-elk) exists
  copy:
    src: "{{ role_path }}/files/docker-elk"
    dest: "{{ stack_path }}"

- name: Ensure stack compose file exists
  template:
    src: "docker-compose.yml.j2"
    dest: "{{ stack_path }}/docker-elk/docker-compose.yml"

- name: Ensure stack compose env file exists
  template:
    src: ".env.j2"
    dest: "{{ stack_path }}/docker-elk/.env"

- name: Ensure docker-elk/setup/entrypoint.sh file is executable
  file:
    path: "{{ stack_path }}/docker-elk/setup/entrypoint.sh"
    mode: '0754'

- name: Ensure the stack is up
  shell: "docker-compose up setup ; docker-compose up -d"
  args:
    chdir: "{{ stack_path }}/docker-elk"

- name: Ensure Kibana UI (http://{{ inventory_hostname }}:{{ kibana_host_port }}/) is available
  uri:
    url: "http://localhost:{{ kibana_host_port }}/"
    method: GET
    status_code:
      - 200
  register: uri_output
  until: uri_output.status == 200
  retries: 12 # Retries for 12 * 5 seconds = 60 seconds
  delay: 5 # Retry every 5 seconds
