---
# handlers file for docker-nifi

- name: Restart rsyslog.service
  service:
    name: rsyslog
    state: restarted

- name: Restart filebeat.service
  service:
    name: filebeat
    state: restarted

